const LAMBDA_MCQ_NODE_API_URL = "https://ieetpwfoci.execute-api.us-east-1.amazonaws.com/prod/v2";
const LAMBDA_MCQ_GO_API_URL = "https://ieetpwfoci.execute-api.us-east-1.amazonaws.com/prod/v2";

export const Types = [
  { id: 2, name: "CLS6-TELUGU" },
  { id: 3, name: "CLS6-HINDI" },
  { id: 4, name: "CLS6-ENGLISH" },
  { id: 5, name: "CLS6-MATHS" },
  { id: 6, name: "CLS6-SCIENCE" },
  { id: 7, name: "CLS6-SOCIAL" },
  { id: 8, name: "CLS7-TELUGU" },
  { id: 9, name: "CLS7-HINDI" },
  { id: 10, name: "CLS7-ENGLISH" },
  { id: 11, name: "CLS7-MATHS" },
  { id: 12, name: "CLS7-SCIENCE" },
  { id: 13, name: "CLS7-SOCIAL" },
  { id: 14, name: "CLS8-TELUGU" },
  { id: 15, name: "CLS8-HINDI" },
  { id: 16, name: "CLS8-ENGLISH" },
  { id: 17, name: "CLS8-MATHS" },
  { id: 18, name: "CLS8-SCIENCE" },
  { id: 19, name: "CLS8-SOCIAL" },
  { id: 20, name: "CLS9-TELUGU" },
  { id: 21, name: "CLS9-HINDI" },
  { id: 22, name: "CLS9-ENGLISH" },
  { id: 23, name: "CLS9-MATHS" },
  { id: 24, name: "CLS9-SCIENCE" },
  { id: 25, name: "CLS9-SOCIAL" },
  { id: 26, name: "CLS10-TELUGU" },
  { id: 27, name: "CLS10-HINDI" },
  { id: 28, name: "CLS10-ENGLISH" },
  { id: 29, name: "CLS10-MATHS" },
  { id: 30, name: "CLS10-SCIENCE" },
  { id: 31, name: "CLS10-SOCIAL" },
  { id: 32, name: "CLS10-BRIDGE" },
  { id: 33, name: "CLS10-POLYTECHNIC" },
  { id: 34, name: "CLS10-FORMULAS" },
  { id: 35, name: "CLS11-MPC-PHYSICS" },
  { id: 36, name: "CLS11-MPC-MATHS1A" },
  { id: 37, name: "CLS11-MPC-MATHS1B" },
  { id: 38, name: "CLS11-MPC-CHEMISTRY" },
  { id: 39, name: "CLS11-MPC-EAMCET" },
  { id: 40, name: "CLS11-MPC-JEEMAINS" },
  { id: 41, name: "CLS11-MPC-JEEADV" },
  { id: 42, name: "CLS12-MPC-PHYSICS" },
  { id: 43, name: "CLS12-MPC-MATHS2A" },
  { id: 44, name: "CLS12-MPC-MATHS2B" },
  { id: 45, name: "CLS12-MPC-CHEMISTRY" },
  { id: 46, name: "CLS12-MPC-EAMCET" },
  { id: 47, name: "CLS12-MPC-JEEMAINS" },
  { id: 48, name: "CLS12-MPC-JEEADV" },
  { id: 49, name: "CLS11-BIPC-PHYSICS" },
  { id: 50, name: "CLS11-BIPC-BOTANY" },
  { id: 51, name: "CLS11-BIPC-ZOOLOGY" },
  { id: 52, name: "CLS11-BIPC-CHEMISTRY" },
  { id: 53, name: "CLS11-BIPC-EAPCET" },
  { id: 54, name: "CLS11-BIPC-NEET" },
  { id: 55, name: "CLS12-BIPC-PHYSICS" },
  { id: 56, name: "CLS12-BIPC-BOTANY" },
  { id: 57, name: "CLS12-BIPC-ZOOLOGY" },
  { id: 58, name: "CLS12-BIPC-CHEMISTRY" },
  { id: 59, name: "CLS12-BIPC-EAPCET" },
  { id: 60, name: "CLS12-BIPC-NEET" }
];



export default LAMBDA_MCQ_NODE_API_URL;
export { LAMBDA_MCQ_GO_API_URL };